apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: carol
  namespace: prometheus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: carol
  namespace: prometheus
rules:
- apiGroups: ["*"]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: carol
  namespace: prometheus
subjects:
- kind: ServiceAccount
  name: carol
  namespace: prometheus
roleRef:
  kind: ClusterRole
  name: carol
  apiGroup: rbac.authorization.k8s.io