apiVersion: v1
kind: ServiceAccount
metadata:
  name: bob
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bob
  namespace: default
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bob
  namespace: default
subjects:
- kind: ServiceAccount
  name: bob
  namespace: default
roleRef:
  kind: ClusterRole
  name: bob
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dave
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dave
  namespace: default
rules:
- apiGroups: [""]
  resources: [""]
  verbs: [""]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dave
  namespace: default
subjects:
- kind: ServiceAccount
  name: dave
  namespace: default
roleRef:
  kind: ClusterRole
  name: dave
  apiGroup: rbac.authorization.k8s.io